const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.Camera3D,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetMirrored
	];
};
self.C3_JsPropNameTable = [
	{Fundo: 0},
	{EntradaDeTexto: 0},
	{imageremovebgpreview: 0},
	{Texto: 0},
	{Sprite: 0},
	{Plataforma: 0},
	{PLAY: 0},
	{Título: 0},
	{Creditos: 0},
	{Sprite2: 0},
	{voltar: 0},
	{Text: 0},
	{Toque: 0},
	{Play2: 0},
	{Créditos: 0},
	{Play3: 0},
	{playy: 0},
	{imageremovebgpreview11: 0},
	{imageremovebgpreview12: 0},
	{imageremovebgpreview13: 0},
	{imageremovebgpreview2: 0},
	{Vídeo: 0},
	{imageremovebgpreview3: 0},
	{Câmera3D: 0},
	{Interpolação: 0},
	{TelaTranscao: 0},
	{Sprite3: 0},
	{imageremovebgpreview4: 0},
	{imageremovebgpreview5: 0},
	{imageremovebgpreview6: 0},
	{Pixel_art_old_computer_vector_icon_for_8bit_game_on_white_backgroundremovebgpreview: 0},
	{imageremovebgpreview7: 0},
	{ChatGPTImage22DeAbrDe202522_25_: 0},
	{Gemini_Generated_Image_x6xfblx6xfblx6xf: 0},
	{Gemini_Generated_Image_4geigp4geigp4gei: 0},
	{Tartaruga_de_costa__lá_ele_removebgpreview: 0},
	{Vídeo2: 0},
	{Sprite4: 0},
	{plano: 0},
	{Sólido: 0},
	{plataforma: 0},
	{CentrarEm: 0},
	{tartarugabasica: 0},
	{Senóide: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{buraco: 0},
	{barreira: 0},
	{pastnha: 0},
	{fundoarquivo: 0},
	{Teclado: 0},
	{Girar: 0},
	{gira: 0},
	{Projétil: 0},
	{Física: 0},
	{bolinha: 0},
	{fundobeje: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{bola: 0},
	{cubo: 0},
	{Sprite7: 0},
	{cone: 0},
	{DestruirForaDoLayout: 0},
	{Sprite8: 0},
	{undertale: 0},
	{trocarSom: 0},
	{backgroundpreto: 0},
	{viloesjudastraidor: 0},
	{cu: 0},
	{CapturaDeTela: 0},
	{cus: 0},
	{Vídeo3: 0},
	{TransitionType: 0}
];

self.InstanceType = {
	Fundo: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	imageremovebgpreview: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	PLAY: class extends self.IButtonInstance {},
	Título: class extends self.ITextInstance {},
	Creditos: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	voltar: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	Toque: class extends self.IInstance {},
	Play2: class extends self.ISpriteInstance {},
	Créditos: class extends self.ISpriteInstance {},
	Play3: class extends self.ISpriteInstance {},
	playy: class extends self.ISpriteInstance {},
	imageremovebgpreview11: class extends self.ISpriteInstance {},
	imageremovebgpreview12: class extends self.ISpriteInstance {},
	imageremovebgpreview13: class extends self.ISpriteInstance {},
	imageremovebgpreview2: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	imageremovebgpreview3: class extends self.ISpriteInstance {},
	Câmera3D: class extends self.IInstance {},
	TelaTranscao: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	imageremovebgpreview4: class extends self.ISpriteInstance {},
	imageremovebgpreview5: class extends self.ISpriteInstance {},
	imageremovebgpreview6: class extends self.ISpriteInstance {},
	Pixel_art_old_computer_vector_icon_for_8bit_game_on_white_backgroundremovebgpreview: class extends self.ISpriteInstance {},
	imageremovebgpreview7: class extends self.ISpriteInstance {},
	ChatGPTImage22DeAbrDe202522_25_: class extends self.ISpriteInstance {},
	Gemini_Generated_Image_x6xfblx6xfblx6xf: class extends self.ISpriteInstance {},
	Gemini_Generated_Image_4geigp4geigp4gei: class extends self.ISpriteInstance {},
	Tartaruga_de_costa__lá_ele_removebgpreview: class extends self.ISpriteInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	plano: class extends self.ITiledBackgroundInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	tartarugabasica: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	buraco: class extends self.ITiledBackgroundInstance {},
	barreira: class extends self.ITiledBackgroundInstance {},
	pastnha: class extends self.ITiledBackgroundInstance {},
	fundoarquivo: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	gira: class extends self.ITiledBackgroundInstance {},
	bolinha: class extends self.ITiledBackgroundInstance {},
	fundobeje: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bola: class extends self.ISpriteInstance {},
	cubo: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	cone: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	undertale: class extends self.IInstance {},
	trocarSom: class extends self.ISpriteInstance {},
	backgroundpreto: class extends self.ITiledBackgroundInstance {},
	viloesjudastraidor: class extends self.ISpriteInstance {},
	cu: class extends self.ISpriteInstance {},
	CapturaDeTela: class extends self.ISpriteInstance {},
	cus: class extends self.ISpriteInstance {},
	Vídeo3: class extends self.IWorldInstance {}
}